dist: bionic
arch: amd64
language: c

env:
  global:
   - secure: "GTi+zMeM0hbOagdiby24Zx1jG0mhagr5xDVa4PdEf0WDww9R0r5Ek42dUTDDN12krNR3PQBhMUDVh+9OibcEpiU4fAiaOAHiWGeTtPdkloA1arW6YBCOzcLjzurQ84pygtMAmlKvRN8xr48wMXBz29TL8divJzXhSvc5QI6jBcFZuCQ/hmjlDVmduVmf0p2NyGhy7Y10IiIhIIo/WwPgL4vEKFCTDHMxwywIr+1E2E8LV+Fw+S5WK/5ssKy8f3E3dpnNpm7UU2eGIjU0GBoAZsd32C+iTof642omds5HNSm/57MAupq+6NYCloYQ8wn6WtKpHLx9OdiAidKoUTvAtW1FnY3rfyQlDKcM4qBjcTeLTQ0yziFD91z4AaDfpfhOPwz0ZpNLQ8ZzYQs9TtHRAQHYOMq8wDQjZMF/AnkO5bUGxZVInrmK6usETKbO4mzU1ot2DQ7jmHbreyQqgAQXo4VjuZ/SS0zLPYioUoMO5p5WhhrsSmnnmJBaf6lEUXhPIyAgAMJHOdB+g4LbgQ1eIyg/Kix/eAz/ZNM67RvBdoTAmccJSziwx0kOpVETSbn1STqNhF0AFWy7JsOF+DwKGf7OeAATzlwX7fiswDy43oPzcYivhOB77/dVpdzkRn0JDp1+P+TdHD+zHBEdwVt9433442YlEi7kKzEoRcVtalM="

addons:
  apt:
    sources:
    - sourceline: 'ppa:dqlite/master'
    packages:
    - lcov
    - libsqlite3-dev
    - libuv1-dev
    - libraft-dev

  coverity_scan:
    build_script_url: https://dl.stgraber.org/coverity_travis.sh
    project:
      name: "canonical/dqlite"
      description: "Embeddable and replicated SQL database"

    # Where email notification of build analysis results will be sent
    notification_email: free.ekanayaka@canonical.com

    build_command_prepend: "autoreconf -i && ./configure"
    build_command: "make"
    branch_pattern: master

compiler:
  - gcc

script:
  - autoreconf -i
  - ./configure --enable-debug --enable-code-coverage --enable-sanitize
  - CFLAGS=-O0
  - make
  - make check || (cat ./test-suite.log && false)
  - if [ $TRAVIS_COMPILER = gcc ]; then make code-coverage-capture; fi
after_success:
  - bash <(curl -s https://codecov.io/bash) -g "./test*"
